# Generated by Django 4.1.1 on 2022-10-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('ttl', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('fakultas', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=150)),
                ('alamat', models.CharField(max_length=250)),
            ],
        ),
    ]
