# Generated by Django 4.1.1 on 2022-10-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=20)),
                ('materi1', models.CharField(max_length=200)),
                ('materi2', models.CharField(max_length=200)),
                ('materi3', models.CharField(max_length=200)),
                ('materi4', models.CharField(max_length=200)),
                ('materi5', models.CharField(max_length=200)),
            ],
        ),
    ]
