# Generated by Django 4.1.1 on 2022-10-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materi',
            old_name='materi1',
            new_name='nama_materi',
        ),
        migrations.RemoveField(
            model_name='materi',
            name='hari',
        ),
        migrations.RemoveField(
            model_name='materi',
            name='materi2',
        ),
        migrations.RemoveField(
            model_name='materi',
            name='materi3',
        ),
        migrations.RemoveField(
            model_name='materi',
            name='materi4',
        ),
        migrations.RemoveField(
            model_name='materi',
            name='materi5',
        ),
        migrations.AddField(
            model_name='materi',
            name='link_video',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
